### PR TITLE
auto close client builders

### PR DESCRIPTION
**Pull request by rotty3000**
Signed-off-by: Raymond Auge <rotty3000@apache.org>

### CODE REVIEW

**Comment by rotty3000** [comment]
What do you think about this change @csierra ? Does it make sense to close the builders? I fear the underlying impls might be leaking.

**Comment by rotty3000** [comment]
I should be able to write a test that proves this one way or the other.

**Comment by csierra** [comment]
do you think we should keep track of all the clients and make sure to close them if the user did not?

**Comment by csierra** [comment]
because if that's the case I guess our only chance is to use a reference queue

**Comment by rotty3000** [comment]
perhaps it would be wise to start with a test that confirms clients are un-closed (and not GC'd, i.e. memory leak)

**Pull request closed without merging**
