### PR TITLE
[tidy up] bnd 4.2.0, use bundle annotations where possible, etc.

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/2/

**Comment by rotty3000** [comment]
closing just to test the `integration` CI build trigger

**Comment by asfgit** [comment]
Can one of the admins verify this patch?

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/4/

**Comment by rotty3000** [comment]
testing CI again..

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/5/

**Comment by rotty3000** [comment]
again...

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/6/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-Integrations/44/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/7/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-Integrations/45/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/8/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-Integrations/46/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/9/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-Integrations/47/

**Comment by asfgit** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://builds.apache.org/job/Aries-JAX-RS-Whiteboard-pr/10/

**Pull request merged**
